"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { usePathname,useRouter } from "next/navigation";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isAccess, setIsAccess] = useState<boolean>(false)
  const pathName = usePathname();
  const router = useRouter()
  const token = localStorage.getItem("token")

  useEffect(() => {
    if (pathName === "/") {
      if (token) { setIsAccess(true) } 
      else { 
        setIsAccess(false)
        localStorage.clear()
        router.push("/signin")
       }
    }else{
      setIsAccess(true)
    }
  }, [pathName])

  return (
    <html lang="en">
      { isAccess ?  <body className={inter.className}>{children}</body> : <></>}
      <ToastContainer />
    </html>
  );
}
